services:
  sicktoolbox:
    build: .
    image: steventango/sicktoolbox
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    network_mode: host
    command: rosrun sicktoolbox_wrapper sicklms _port:=/dev/ttyUSB0 _baud:=38400
